name: CI
on:
  pull_request:

jobs:
  cargo-test:
    strategy:
      # Prevent GitHub from cancelling all in-progress jobs when a matrix job fails.
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          override: true
          toolchain: stable
          profile: minimal
      # Smart caching for Rust projects.
      # Includes workaround for macos cache corruption.
      # - https://github.com/rust-lang/cargo/issues/8603
      # - https://github.com/actions/cache/issues/403
      - uses: Swatinem/rust-cache@v1

      # Real CI work starts here
      - name: Build workspace
        run: cargo build

      # Workspace tests
      - name: Run workspace unit tests
        run: cargo test --lib --all -j6
      - name: Run workspace doc tests
        run: cargo test --doc --all -j6
